# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/purpose': 'Frameworks/6.24'
    'frameworks/qqc2-desktop-style': 'Frameworks/6.24'

- 'on': ['Linux', 'FreeBSD', 'Android']
  'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kirigami': 'Frameworks/6.24'
    'frameworks/kitemmodels': 'Frameworks/6.24'
    'libraries/kirigami-addons': 'v1.11.0'
    'libraries/mpvqt': '@latest'
    'third-party/qtkeychain': '@latest'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
